moto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path('', include('shop_app.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ModelView.as_view()),
    path('filter/', views.FilterModelsView.as_view(), name='filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/', views.ModelDetailView.as_view(), name='model_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('racer/<str:slug>/', views.RacerView.as_view(), name='racer_detail'),
]

shop_app/models.py
from django.db import models
from datetime import date

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Racer(models.Model):
    """Гонщики + Производители"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="racers/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('racer_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Гонщики и Производители"
        verbose_name_plural = "Гонщики и Производители"


class Season(models.Model):
    """Сезон"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Сезон"
        verbose_name_plural = "Сезоны"


class Model(models.Model):
    """Модель"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default="")
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="models/")
    year = models.PositiveSmallIntegerField("Дата сборки", default=2004)
    country = models.CharField("Страна", max_length=30)
    manufacturers = models.ManyToManyField(Racer, verbose_name="Производитель", related_name="moto_manufacturer")
    racers = models.ManyToManyField(Racer, verbose_name="Гонщики", related_name="moto_racer")
    season = models.ManyToManyField(Season, verbose_name="Сезон")
    world = models.DateField("Выход на рынок", default=date.today)
    price = models.PositiveIntegerField("Цена за рубежом", default=0, help_text="Указать сумму в долларах")
    price_in_rus = models.PositiveIntegerField("Цена в России", default=0, help_text="Указать сумму в долларах")
    price_market = models.PositiveIntegerField("Цена перекупом", default=0, help_text="Указать сумму в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('model_detail', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Модель"
        verbose_name_plural = "Модели"


class Image(models.Model):
    """Фото"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="moto_images/")
    model = models.ForeignKey(Model, verbose_name="Модель", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Фото модели"
        verbose_name_plural = "Фото модели"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.PositiveIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ['-value']


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="Звезда")
    model = models.ForeignKey(Model, on_delete=models.CASCADE, verbose_name="Модель")

    def __str__(self):
        return f"{self.star} - {self.model}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey("self", verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    model = models.ForeignKey(Model, verbose_name="Модель", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.model}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

shop_app/forms.py
from django import forms
from .models import Reviews, RatingStar, Rating


class ReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    start = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('star',)

shop_app/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from .models import Model, Category, Racer, Season, Rating
from .forms import ReviewForm, RatingForm
# Create your views here.


class SeasonYear():
    """Фильтр Сезоны, года, категории"""
    def get_seasons(self):
        return Season.objects.all()

    def get_years(self):
        return Model.objects.filter(draft=False).values('year')

    def get_categories(self):
        return Category.objects.all()


class ModelView(SeasonYear, ListView):
    """Список моделей"""
    model = Model
    queryset = Model.objects.filter(draft=False)
    paginate_by = 20



class ModelDetailView(SeasonYear, DetailView):
    """Полное описание модели"""
    model = Model
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        return context



class AddReview(View):
    """Отправка отзыва"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        model = Model.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.model = model
            form.save()
        return redirect(model.get_absolute_url())


class RacerView(SeasonYear, DetailView):
    """Вывод информации о гонщике"""
    model = Racer
    template_name = 'shop_app/racer.html'
    slug_field = 'name'


class FilterModelsView(SeasonYear, ListView):
    """Фильтр моделей"""
    paginate_by = 20
    def get_queryset(self):
        queryset = Model.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(season__in=self.request.GET.getlist('season')) |
            Q(category__in=self.request.GET.getlist('category'))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["season"] = ''.join([f"season={x}&" for x in self.request.GET.getlist("season")])
        context["category"] = ''.join([f"category={x}&" for x in self.request.GET.getlist("category")])
        return context



class AddStarRating(View):
    """Добавление рейтинга модели"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                model_id=int(request.POST.get('model')),
                defaults={'star_id': int(request.POST.get('star'))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    """Поиск моделей"""
    paginate_by = 20
    def get_queryset(self):
        return Model.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f'q={self.request.GET.get("q")}&'
        return context

shop_app/templates/shop_app/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block model %}
            {% endblock model %}
        </div>
        </div>
    </section>
{% endblock content %}

shop_app/templates/shop_app/model_detail.html
{% extends 'shop_app/base.html' %}
{% load static %}
{% block title %} {{ model.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block model %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ model.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ model.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Дата сборки:</b> {{ model.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ model.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ model.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Производитель:</b>
                            {% for manufacturer in model.manufacturers.all %}
                                <a href="{{ manufacturer.get_absolute_url }}">
                                    {{ manufacturer.name }}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Гонщики:</b>
                        {% for racer in model.racers.all %}
                            <a href="{{ racer.get_absolute_url }}">
                                {{ racer.name }}
                            </a>
                        {% endfor %}
                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Сезон:</b>
                        {% for season in model.season.all %}
                            {{ season.name }}
                        {% endfor %}
                    </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Выход на рынок:</b> {{ model.world }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Цена за рубежом:</b> ${{ model.price }}</span></li>
                    <li style="list-style: none">
                        <span><b>Цена в России :</b> ${{ model.price_in_rus }}</span></li>
                    <li style="list-style: none">
                        <span><b>Цена перекупом:</b> ${{ model.price_market }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ model.id }}" name="model">
                            <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating {{ v }}" type="radio" name="star"
                                        value="{{ k }}">
                                    <label for='rating{{ v }}'>{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
                        </form>
                    </li>
                </ul>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent">
                                        <span class="fa fa-facebook-f"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent">
                                        <span class="fa fa-twitter"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent">
                                        <span class="fa fa-dribbble"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О модели {{ model.title }}
            </h3>
            <p>
                {% for image in model.image_set.all %}
                <img src="{{ image.image.url }}" class="img-moto-image"
                     alt="{{ image.description }}">
                {% endfor  %}
            </p>
            <p class="editContent">
                {{ model.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent">
                        <span class="sub-tittle editContent">{{ model.reviews_set.count }}</span>Оставить
                        отзыв</h3>
                    <form action="{% url 'add_review' model.id %}" method="post" class="mt-4"
                          id="formReview">
                        {% csrf_token %}
                        <input type="hidden" name="parent" id="contactparent" value="">
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in model.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                        <div class="media mt-5 editContent">
                            <a class="pr-3" href="#">
                                <img src="{% static 'images/te2.jpg' %}" class="img-fluid"
                                    alt="image">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                            <p class="mt-2 editContent"> {{ rew.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
        <script>
            function addReview(name, id){
                document.getElementById('contactparent').value = id;
                document.getElementById('contactcomment').innerText = `${name},`
            }
        </script>
{% endblock model %}

shop_app/templates/shop_app/model_list.html
{% extends 'shop_app/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block model %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for model in model_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ model.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ model.get_absolute_url }}"
                                   class="editContent">
                                    {{ model.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ model.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock model %}

shop_app/templates/shop_app/racer.html
{% extends 'shop_app/base.html' %}
{% load static %}
{% block title %} {{ racer.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block model %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ racer.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ model.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ racer.age }} лет</span></li>
                    <li>
                        <span><b>Производитель:</b>
                            {% for model in racer.moto_manufacturer.all %}
                                {{ model.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Гонщик:</b>
                            {% for model in racer.moto_racer.all %}
                                {{ model.title }}
                            {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ racer.name }}
            </h3>
            <p class="editContent">
                {{ racer.description|safe }}
            </p>
        </div>
    </div>
{% endblock model %}